### ISSUE TITLE
Issue with Python sys and os commands and relative and exact directory paths for Windows

### ISSUE THREAD

**Issue by mpw07458** [mpw07458/K8S-Deploy#6]
Changes and remediation needs to be made to any python sys or os modules to ensure both windows and linux paths work for files

Trace is here, cannot find path because bash shell "../<dir>" is used
must support relative and exact paths for both linux and  windows by checking OS=win OS=linux

Traceback (most recent call last):
  File "K8S_App_Shell_OS.py", line 512, in <module>
    k8s_shell.shell_health_check()
  File "K8S_App_Shell_OS.py", line 86, in shell_health_check
    docker_version(self)
  File "K8S_App_Shell_OS.py", line 492, in docker_version
    VersionDict = client.version(self)
  File "C:\Python27\lib\site-packages\docker\client.py", line 186, in version
    return self.api.version(*args, **kwargs)
  File "C:\Python27\lib\site-packages\docker\api\daemon.py", line 172, in version
    return self._result(self._get(url), json=True)
  File "C:\Python27\lib\site-packages\docker\utils\decorators.py", line 46, in inner
    return f(self, *args, **kwargs)
  File "C:\Python27\lib\site-packages\docker\api\client.py", line 194, in _get
    return self.get(url, **self._set_request_timeout(kwargs))
  File "C:\Python27\lib\site-packages\requests\sessions.py", line 521, in get
    return self.request('GET', url, **kwargs)
  File "C:\Python27\lib\site-packages\requests\sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Python27\lib\site-packages\requests\sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "C:\Python27\lib\site-packages\requests\adapters.py", line 440, in send
    timeout=timeout
  File "C:\Python27\lib\site-packages\urllib3\connectionpool.py", line 601, in urlopen
    chunked=chunked)
  File "C:\Python27\lib\site-packages\urllib3\connectionpool.py", line 357, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "C:\Python27\lib\httplib.py", line 1042, in request
    self._send_request(method, url, body, headers)
  File "C:\Python27\lib\httplib.py", line 1082, in _send_request
    self.endheaders(body)
  File "C:\Python27\lib\httplib.py", line 1038, in endheaders
    self._send_output(message_body)
  File "C:\Python27\lib\httplib.py", line 882, in _send_output
    self.send(msg)
  File "C:\Python27\lib\httplib.py", line 844, in send
    self.connect()
  File "C:\Python27\lib\site-packages\docker\transport\npipeconn.py", line 31, in connect
    sock.connect(self.npipe_path)
  File "C:\Python27\lib\site-packages\docker\transport\npipesocket.py", line 22, in wrapped
    return f(self, *args, **kwargs)
  File "C:\Python27\lib\site-packages\docker\transport\npipesocket.py", line 50, in connect
    win32pipe.WaitNamedPipe(address, self._timeout)
pywintypes.error: (2, 'WaitNamedPipe', 'The system cannot find the file specified.')

**Comment by mpw07458** [comment]
I added code in v0.935 to fix the absolute path issues and code to do logging
